if (FALSE)
{
  library(magrittr)
  
  overview <- kwb.fisbroker::get_dataset_overview()
  
  metadata <- read_all_metadata(overview)
  
  View(metadata)

  addresses <- metadata$value[metadata$parameter == "Rechneradresse"]
  
  basename(addresses)
}

# read_all_metadata ------------------------------------------------------------

#' Read Metadata based on Overview on FIS Broker Datasets
#' 
#' @param overview overview tibble as retrieved by \code{\link{get_dataset_overview}}, 
#' (default: \code{\link{get_dataset_overview}})
#' @param dbg whether or not to show debug messages (default: TRUE)
#' @return tibble with all metdata information
#' @export
#' @importFrom kwb.utils moveColumnsToFront rbindAll
#' @importFrom stats setNames
#' @importFrom utils URLdecode
#' @examples 
#' \dontrun{
#' overview <- kwb.fisbroker::get_dataset_overview()
#' overview_atom <- overview[overview$type == "ATOM",]
#' metadata_atom <- kwb.fisbroker::read_all_metadata(overview_atom)
#' overview_wfs <- overview[overview$type == "WFS",]
#' metadata_wfs <- kwb.fisbroker::read_all_metadata(overview_wfs)
#' overview_wms <- overview[overview$type == "WMS",]
#' metadata_wms <- kwb.fisbroker::read_all_metadata(overview_wms)
#' }
read_all_metadata <- function(
    overview = get_dataset_overview(), 
    dbg = TRUE
)
{
  #kwb.utils::assignPackageObjects("kwb.fisbroker")
  
  overview %>% 
    create_info_page_hrefs() %>%
    lapply(function(href) read_metadata(url = href)) %>%
    stats::setNames(utils::URLdecode(overview$identifier)) %>%
    kwb.utils::rbindAll("identifier") %>%
    kwb.utils::moveColumnsToFront("identifier")
}

# create_info_page_hrefs -------------------------------------------------------

#' Create Full URLs to Info Pages about Datasets in Overview Table
#' 
#' @inheritParams read_all_metadata
#' @return vector with hrefs
#' @export
#' @importFrom kwb.utils catAndRun getAttribute multiSubstitute
#' @importFrom utils URLencode
  create_info_page_hrefs <- function(overview, dbg = TRUE)
{
  session_id <- kwb.utils::getAttribute(overview, "session_id")
  
  kwb.utils::catAndRun(
    "Creating URLs to info pages",
    dbg = dbg, 
    expr = {
      get_urls(key. = "href_type", sid = session_id) %>% 
        kwb.utils::multiSubstitute(list("<(type|id)>" = "%s")) %>%
        sprintf(overview$type, utils::URLencode(overview$identifier))
    }
  )
}

# read_metadata ----------------------------------------------------------------

#' Read metadata
#'
#' @param dataset_id id of wfs dataset (default: "s_wfs_alkis_bezirk"). Needs to
#' checked out manually as described below:
#' 1. Go to: \url{https://fbinter.stadt-berlin.de/fb/}
#' 2. Click on a "WFS" or "WMS" Dataset
#' 3. Read the content of \code{Rechneraddresse} in the opened tab. The basename
#' of the url is the required dataset id!
#' @param service_type either "WFS" or "WMS" (default: "WFS")
#' @param encoding encoding of metadata FIS-Broker site (default: "Windows-1252")
#' @param dbg print debug messages (default: TRUE)
#' @param url optional. URL to web resource from which to load metadata. 
#'   by default generated by the function
#' @seealso \url{https://fbinter.stadt-berlin.de/fb/berlin/service_intern.jsp?id=s_wfs_alkis_bezirk@@senstadt&type=WFS}
#' @return tibble with metadata for provided dataset_id
#' @importFrom rvest read_html
#' @export
#' @examples
#' ### One Dataset
#' berlin_bezirke_metadata <- read_metadata(dataset_id = "s_wfs_alkis_bezirk")
#' berlin_bezirke_metadata
#' 
#' ### Multiple
#' ids_wfs <- readLines(system.file("extdata/ids_wfs.txt", 
#' package = "kwb.fisbroker"))
#' 
#' wfs_meta_list <- setNames(lapply(ids_wfs, function(id) {
#' kwb.fisbroker::read_metadata(id)}),
#' ids_wfs)
#' 
#' wfs_meta <- dplyr::bind_rows(wfs_meta_list, .id = "id_wfs")
#' 
#' wfs_meta
read_metadata <- function(
    dataset_id = "s_wfs_alkis_bezirk", 
    service_type = "WFS",
    encoding = "Windows-1252",
    dbg = TRUE,
    url = NULL
) 
{
  if (is.null(url)) {
    url <- get_urls(
      key. = "href_meta", 
      id = dataset_id, 
      type = service_type
    )
  }

  stopifnot(length(url) == 1L)
  
  url %>%
    get_html_as_text(dbg = dbg) %>%
    rvest::read_html(encoding = encoding) %>%
    parse_for_metadata(dbg = dbg)
}

# parse_for_metadata -----------------------------------------------------------

#' Parse HTML Tree for Metadata 
#' 
#' @param x object of class "xml_node"
#' @param dbg whether or not to show debug messages
#' @return tibble with metadata
#' @keywords internal
#' @noMd
#' @noRd
#' @importFrom rvest html_elements html_text
#' @importFrom stats setNames
#' @importFrom kwb.utils moveColumnsToFront rbindAll
parse_for_metadata <- function(x, dbg = TRUE)
{
  stopifnot(inherits(x, "xml_node"))
  
  titles <- x %>%
    rvest::html_elements(xpath = "//span[contains(@class, 'titel')]") %>%
    rvest::html_text()
  
  tables <- rvest::html_elements(x, "table")
  
  stopifnot(length(tables) == length(titles))
  
  data_frames <- lapply(
    stats::setNames(tables, titles), 
    table_to_data_frame, 
    dbg = dbg
  )
  
  data_frames %>%
    kwb.utils::rbindAll(nameColumn = "section") %>%
    kwb.utils::moveColumnsToFront("section")
}

# table_to_data_frame ----------------------------------------------------------

#' HTML Table to Data Frame
#' 
#' @param table_node table_node
#' @param dbg whether or not to show debug messages
#' @return data frame with table values
#' @keywords internal
#' @noMd
#' @noRd
#' @importFrom kwb.utils asNoFactorDataFrame catAndRun multiSubstitute
#' @importFrom kwb.utils naToLastNonNa
#' @importFrom rvest html_elements
#' @importFrom stats setNames
table_to_data_frame <- function(table_node, dbg = TRUE)
{
  #table_node <- tables[[3L]]
  stopifnot(inherits(table_node, "xml_node"))
  
  table_fields <- table_node %>%
    rvest::html_elements("tr") %>%
    lapply(function(x) {
      sapply(rvest::html_elements(x, "td"), rvest::html_text)
    })
  
  has_two_fields <- lengths(table_fields) == 2L
  
  if (!all(has_two_fields)) {
    table_fields <- kwb.utils::catAndRun(
      sprintf(
        "Removing %d row(s) with not exactly two fields",
        sum(!has_two_fields)
      ),
      dbg = dbg,
      table_fields[has_two_fields]
    )
  }
  
  data <- table_fields %>%
    unlist() %>%
    replace_non_breaking_spaces() %>%
    trim_end_of_lines() %>%
    matrix(ncol = 2L, byrow = TRUE) %>%
    kwb.utils::asNoFactorDataFrame() %>%
    stats::setNames(c("parameter", "value"))
  
  data[["parameter"]] <- data[["parameter"]] %>%
    kwb.utils::multiSubstitute(list(":$" =  "", "^\\s*$" = NA)) %>%
    kwb.utils::naToLastNonNa()
  
  data
}
